name = "Ecosystem"
uuid = "e77cd98c-0b06-4577-a1b1-f35164dcc344"
authors = ["Niklas Heim <heim.niklas@gmail.com> and contributors"]
version = "0.1.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
